name: CI - Angular Ecommerce

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # opcional: permite rodar manualmente pelo bot√£o "Run workflow"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install deps (backend)
        run: npm ci

      - name: Run backend tests
        run: npm test || echo "sem testes configurados"

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install deps (frontend)
        run: npm install --legacy-peer-deps

      - name: Build frontend (CI)
        run: npm run build -- --configuration=production

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: [ test-backend, test-frontend ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Registry (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_USER }}/ecommerce-backend:dev
            ${{ secrets.REGISTRY_USER }}/ecommerce-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_USER }}/ecommerce-frontend:dev
            ${{ secrets.REGISTRY_USER }}/ecommerce-frontend:${{ github.sha }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Deploy on EC2 via SSH (kubectl rollout)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/angular-ecommerce-app
            git pull origin master
            cd k8s
            kubectl rollout restart deployment backend -n app-demo
            kubectl rollout restart deployment frontend -n app-demo
